name: README build
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Configure pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: ${{ vars.USER_NAME }}
        run: python today.py
      - name: Commit
        run: |-
          git add .
          git diff
          git config --global user.email "github-actions-bot@echodrift.github.io"
          git config --global user.name "echodrift/GitHub-Actions-Bot"
          git commit -m "Updated README" -a || echo "No changes to commit"
          git push